#!/usr/bin/env bash

#      _                       _                   _
#     (_)                     | |                 | |
#  ___ _ _ __ ___   ___  _ __ | |__  _ __ __ _ ___| |_ _ __ _ __ ___
# / __| | '_ ` _ \ / _ \| '_ \| '_ \| '__/ _` / __| __| '__| '_ ` _ \
# \__ \ | | | | | | (_) | | | | |_) | | | (_| \__ \ |_| |  | | | | | |
# |___/_|_| |_| |_|\___/|_| |_|_.__/|_|  \__, |___/\__|_|  |_| |_| |_|
#                                         __/ |
#                                        |___/

hc() {
    herbstclient "$@"
}

hc emit_hook reload

#xsetroot -solid '#081d3f'


#compton --config ~/.config/compton.conf

# remove all existing keybindings
hc keyunbind --all

# keybindings
# if you have a super key you will be much happier with Mod set to Mod4
#Mod=Mod1    # Use alt as the main modifier
Mod=Mod4   # Use the super key as the main modifier

hc keybind $Mod-Shift-q quit
hc keybind $Mod-Shift-r reload
hc keybind $Mod-Shift-c close
hc keybind $Mod-Return spawn ${TERMINAL:-gnome-terminal} # use your $TERMINAL with xterm as fallback

hc keybind $Mod-l spawn betterlockscreen -l dim
#hc keybind $Mod-l spawn i3lock-fancy
#hc keybind $Mod-Shift-p spawn dmenu_run_hlwm
hc keybind $Mod-Shift-p spawn rofi -show run
hc keybind $Mod-Shift-o spawn rofi -show window
hc keybind $Mod-Shift-u spawn rofi -show ssh
hc keybind $Mod-Shift-i spawn deepin-screenshot
hc keybind $Mod-F1 spawn amixer -q -D pulse sset Master toggle
hc keybind $Mod-F2 spawn amixer -d sset Master 2%-
hc keybind $Mod-F3 spawn amixer -d sset Master 2%+
hc keybind $Mod-F5 spawn brightnessctl s 5%-
hc keybind $Mod-F6 spawn brightnessctl s 5%+

#Spotify control
hc keybind $Mod-F7 spawn dbus-send --print-reply --dest=org.mpris.MediaPlayer2.spotify /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.PlayPause
hc keybind $Mod-F9 spawn dbus-send --print-reply --dest=org.mpris.MediaPlayer2.spotify /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.Next
hc keybind $Mod-F8 spawn dbus-send --print-reply --dest=org.mpris.MediaPlayer2.spotify /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.Previous


# basic movement
# focusing clients
hc keybind $Mod-Left  focus left
hc keybind $Mod-Down  focus down
hc keybind $Mod-Up    focus up
hc keybind $Mod-Right focus right
#hc keybind $Mod-h     focus left
#hc keybind $Mod-j     focus down
#hc keybind $Mod-k     focus up
#hc keybind $Mod-l     focus right

# moving clients
hc keybind $Mod-Shift-Left  shift left
hc keybind $Mod-Shift-Down  shift down
hc keybind $Mod-Shift-Up    shift up
hc keybind $Mod-Shift-Right shift right
#hc keybind $Mod-Shift-h     shift left
#hc keybind $Mod-Shift-j     shift down
#hc keybind $Mod-Shift-k     shift up
#hc keybind $Mod-Shift-l     shift right

# splitting frames
# create an empty frame at the specified direction
hc keybind $Mod-u       split   bottom  0.5
hc keybind $Mod-o       split   right   0.5
# let the current frame explode into subframes
hc keybind $Mod-Control-space split explode

# resizing frames
resizestep=0.05
hc keybind $Mod-Control-h       resize left +$resizestep
hc keybind $Mod-Control-j       resize down +$resizestep
hc keybind $Mod-Control-k       resize up +$resizestep
hc keybind $Mod-Control-l       resize right +$resizestep
hc keybind $Mod-Control-Left    resize left +$resizestep
hc keybind $Mod-Control-Down    resize down +$resizestep
hc keybind $Mod-Control-Up      resize up +$resizestep
hc keybind $Mod-Control-Right   resize right +$resizestep

# tags
tag_names=( {1..9} )
tag_keys=( {1..9} 0 )

hc rename default "${tag_names[0]}" || true
for i in ${!tag_names[@]} ; do
    hc add "${tag_names[$i]}"
    key="${tag_keys[$i]}"
    if ! [ -z "$key" ] ; then
        hc keybind "$Mod-$key" use_index "$i"
        hc keybind "$Mod-Shift-$key" move_index "$i"
    fi
done

# cycle through tags
hc keybind $Mod-period use_index +1 --skip-visible
hc keybind $Mod-comma  use_index -1 --skip-visible

# layouting
hc keybind $Mod-r remove
hc keybind $Mod-s floating toggle
hc keybind $Mod-f fullscreen toggle
hc keybind $Mod-p pseudotile toggle
# The following cycles through the available layouts within a frame, but skips
# layouts, if the layout change wouldn't affect the actual window positions.
# I.e. if there are two windows within a frame, the grid layout is skipped.
hc keybind $Mod-space                                                           \
            or , and . compare tags.focus.curframe_wcount = 2                   \
                     . cycle_layout +1 vertical horizontal max vertical grid    \
               , cycle_layout +1

# mouse
hc mouseunbind --all
hc mousebind $Mod-Button1 move
hc mousebind $Mod-Button2 zoom
hc mousebind $Mod-Button3 resize

# focus
hc keybind $Mod-BackSpace   cycle_monitor
hc keybind $Mod-Tab         cycle_all +1
hc keybind $Mod-Shift-Tab   cycle_all -1
hc keybind $Mod-c cycle
hc keybind $Mod-i jumpto urgent

# theme
hc attr theme.tiling.reset 1
hc attr theme.floating.reset 1
#hc set frame_border_active_color '#1e97bc' 	#lightblue
#hc set frame_border_normal_color '#222222' 	#black
#hc set frame_bg_normal_color '#565656'		#grey
#hc set frame_bg_active_color '#1e97bc' 		#lightblue
hc set frame_border_active_color '#ffb200'      #orange
hc set frame_border_normal_color '#222222'      #black
hc set frame_bg_normal_color '#916500'          #grey
hc set frame_bg_active_color '#ffb200'          #orange

hc set frame_borhc keybind $Mod-Shift-l     shift right

# theme
hc attr theme.tiling.reset 1
hc keybind $Mod-Shift-l     shift right

# theme
hc attr theme.tiling.reset 1
# theme
hc attr theme.tiling.reset 1
der_width 1
hc set always_show_frame 1
hc set frame_bg_transparent 1
hc set frame_transparent_width 0
hc set frame_gap 0
hc set frame_active_opacity 50
hc set frame_normal_opacity 50
hc set frame_border_width 0
hc set frame_border_inner_width 0


#hc attr theme.active.color '#0fd3ff' #lightblue
#hc attr theme.normal.color '#1e3f75' #darkblue
#hc attr theme.urgent.color '#ff0000' #red
#hc attr theme.inner_width 1
#hc attr theme.inner_color '#000000' #black
#hc attr theme.border_width 3
#hc attr theme.floating.border_width 4
#hc attr theme.floating.outer_width 1
#hc attr theme.floating.outer_color '#000000' #black
#hc attr theme.active.inner_color '#1e3f75' #darkblue
#hc attr theme.active.outer_color '#1e3f75' #darkblue
#hc attr theme.background_color '#1e3f75' #darkblue

hc attr theme.active.color '#ffb200' #orange
hc attr theme.normal.color '#996b00' #darkorange
hc attr theme.urgent.color '#ff0000' #red
hc attr theme.inner_width 3
hc attr theme.inner_color '#000000' #black
hc attr theme.border_width 4
hc attr theme.floating.border_width 1
hc attr theme.floating.outer_width 1
hc attr theme.floating.outer_color '#000000' #black
hc attr theme.active.inner_color '#996b00' #darkorange
hc attr theme.active.outer_color '#996b00' #darkorange
hc attr theme.background_color '#996b00' #darkorange


hc set window_gap 10
hc set frame_padding 1
hc set smart_window_surroundings 0
hc set smart_frame_surroundings 1
hc set mouse_recenter_gap 0

# rules
hc unrule -F
#hc rule class=XTerm tag=3 # move all xterms to tag 3
hc rule focus=on # normally focus new clients
hc rule class=firefox tag=3
#hc rule focus=off # normally do not focus new clients
# give focus to most common terminals
#hc rule class~'(.*[Rr]xvt.*|.*[Tt]erm|Konsole)' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' pseudotile=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off

hc rule class=''

# unlock, just to be sure
hc unlock

herbstclient set tree_style '╾│ ├└╼─┐'

# do multi monitor setup here, e.g.:
# hc set_monitors 1280x1024+0+0 1280x1024+1280+0
# or simply:
#hc detect_monitors
#herbstclient set auto_detect_monitors 1

# find the panel
panel=~/.config/herbstluftwm/panel.sh
[ -x "$panel" ] || panel=/etc/xdg/herbstluftwm/panel.sh
for monitor in $(herbstclient list_monitors | cut -d: -f1) ; do
    # start it on each monitor
    "$panel" $monitor &
done

#Autostart
#pkill polybar
#polybar -c ~/.config/herbstluftwm/polytest top & mpd &

feh --bg-fill ~/Pictures/wallpapers/wallor.png
